### ISSUE TITLE
自定义门户功能

### ISSUE THREAD

**Issue by hotlong** [steedos/steedos-project-saas#129]
专业版可以自己配置门户yml，具体规则：
- [x] 增加dashboard对象，用户可以在设置界面维护该对象内容
- [x] 用户可以配置home.dashboard.yml文件，相当于增加一个id为home的dashboard业务对象
- [x] 之前可以在xx.app.yml中配置dashboard属性来给xx应用配置门户界面，作废
- [x] 之前可以通过增加一个空的xx.object.yml文件，写webapp组件并把该组件`registerObjectHomeComponent`到对象，并把该object配置为应用的第一个对象来实现应用首页，保留该功能
- [x] webapp中增加`registerDashboardComponent`功能函数，可以把门户关联到一个或多个应用

> home.dashboard.yml文件格式如下:
```
_id: home
name: 华炎办公
apps: 
  - oa
  - contracts
widgets: 
  - type: instances_pendings
    position: CENTER_TOP
  - type: apps
    position: RIGHT
```
> dashboard对象字段配置如下:
```
name:
  label: 名称
  type: text
  searchable: true
  index: true
  required: true
apps:
  label: 关联应用
  type: lookup
  reference_to: apps
  multiple: true
widgets:
  label: 组件
  type: grid
widgets.$.type:
  label: 类型
  type: lookup
  required: true
widgets.$.position:
  label: 位置
  type: lookup
  required: true
widgets.$.html:
  label: HTML
  type: textarea
  required: false
description:
  label: 描述
  type: textarea
  is_wide: true
```
- 其中widgets.type支持：
```
return [{
    label: "待审核文件",
    value: "instances_pendings",
    icon: "work_type"
  },
  {
    label: "应用程序",
    value: "apps",
    icon: "work_type"
  },
  {
    label: "本周公告",
    value: "announcements_week",
    icon: "work_type"
  },
  {
    label: "今日任务",
    value: "tasks_today",
    icon: "work_type"
  },
  {
    label: "今日日程",
    value: "events_today",
    icon: "work_type"
}];
```
- 其中widgets.position支持：
```
return [{
    label: "左上角",
    value: "CENTER_TOP",
    icon: "topic2"
  },
  {
    label: "左下角左侧",
    value: "CENTER_BOTTOM_LEFT",
    icon: "topic2"
  },
  {
    label: "左下角右侧",
    value: "CENTER_BOTTOM_RIGHT",
    icon: "topic2"
  },
  {
    label: "右边栏",
    value: "RIGHT",
    icon: "topic2"
  }];
```
